export type ElementProfile = {
  number: number;
  symbol: string;
  name: string;
  family: string;
  atomicWeight: string;
  description: string;
  fact: string;
};

export const elements: ElementProfile[] = [
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    family: 'Nonmetal',
    atomicWeight: '1.008',
    description: `For the first element of the periodic table, I felt like we should celebrate those who created the fashion we know today. The LGBTQ+ community has always been at the forefront of fashion, inspiring everything from Yves Saint Laurent’s Le Smoking to voguing and the runway walk, and is finally getting the recognition it deserves. I took inspiration from drag’s delicious maximalism, using RuPaul’s Drag Race and voguing competitions I saw on YouTube as references.`,
    fact: 'Hydrogen is the most abundant element in the universe and the fuel that powers stars.',
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    family: 'Noble gas',
    atomicWeight: '4.0026',
    description: `I feel Helium has a very ethereal quality to it, even though it makes you sound like a chipmunk if you breathe it in. This look was inspired by Anok Yai’s 2024 Met Gala outfit, which was complete with 98,000 Swarovski gems. Helium only has two protons, but its role in astrophysics is worth a zillion crystals to me.`,
    fact: 'Helium was detected in the Sun before it was discovered here on Earth.',
  },
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    family: 'Alkali metal',
    atomicWeight: '6.94',
    description: `It felt right to give the element with an atomic number of three a three-pointed crown. This one mostly came from my own mind—Lithium feels very regal to me, even if it is quite reactive! I feel like this outfit encapsulates both sides of her personality.`,
    fact: 'Lithium is the lightest metal and a key ingredient in rechargeable batteries.',
  },
  {
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    family: 'Alkaline earth',
    atomicWeight: '9.0122',
    description: `We talk a lot about Magnesium, Lithium, Potassium, and every other alkali and alkaline earth metal, but I feel like Beryllium doesn’t get as much press. She’s dressed in complementary colors to stand out, as she still deserves to be noticed!`,
    fact: 'Beryllium is unusually transparent to X-rays, so it is used in specialized imaging windows.',
  },
  {
    number: 5,
    symbol: 'B',
    name: 'Boron',
    family: 'Metalloid',
    atomicWeight: '10.81',
    description: `Boron is silver or black in reality, but it helps regulate temperature like the sea, so I thought I would go with a beachy vibe. The white of her hat and dress mimics bone, and trace amounts of boron do support bone health in the human body.`,
    fact: 'Boron helps make borosilicate glass resistant to sudden changes in temperature.',
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    family: 'Nonmetal',
    atomicWeight: '12.011',
    description: `Carbon is just extra. She’s coal and diamond, regular nonpolar covalent bonds and network bonds. With four valence electrons, she is essential for all life and processes in the body, and deserves to have an incredibly long dress made of charcoal shavings and feathers. Carbon also happens to be the first one of these drawings I did.`,
    fact: 'Diamond and graphite look completely different, but both are made entirely of carbon.',
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    family: 'Nonmetal',
    atomicWeight: '14.007',
    description: `The air we breathe is mostly nitrogen, although humans don’t have much use for it in that form. But nitrogen is one of the most important elements for plant life because it helps make chlorophyll, which plants need for photosynthesis! So we need to put Nitrogen in some comfortable overalls and mossy boots so she can tend to all of her plants!`,
    fact: 'Nitrogen makes up about 78 percent of Earth’s atmosphere.',
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    family: 'Nonmetal',
    atomicWeight: '15.999',
    description: `I took inspiration from 17th-century European fashion for Oxygen. She seems like a fancy lady who wants to be known and loved by all. And she should be—oxygen is essential for basically everything necessary for life!`,
    fact: 'Oxygen makes up about 21 percent of the air and supports most life on Earth.',
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    family: 'Halogen',
    atomicWeight: '18.998',
    description: `Fluorine is drama. Only nine protons and she’s the most reactive element in chemistry. Big hair, ruffles, and fiery colors were the only way to go.`,
    fact: 'Fluorine is the most chemically reactive element in the periodic table.',
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    family: 'Noble gas',
    atomicWeight: '20.180',
    description: `Neon reminded me of the neon lights appearing in cities in the 1920s, which got me thinking about jazz. One of the most influential jazz, blues, and R&B singers, Willie Mae “Big Mama” Thornton, came to mind as the most Neon person I know of. Her 1952 song “Hound Dog” is mostly known as a song by Elvis, and she was denied many of the royalties from her songs. But she remains an absolute queen in all of our hearts, and I think she sang “Hound Dog” way better than Elvis did. Here’s to Big Mama Thornton, a truly Neon gal.`,
    fact: 'Pure neon glows a vivid reddish orange when electricity passes through it.',
  },
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    family: 'Alkali metal',
    atomicWeight: '22.990',
    description: `Sodium is very reactive and dangerous on his own, but when he’s with pals like Chlorine, he’s the chillest guy in town. Sodium’s look is loosely based on 1970s counterculture, complete with a leather jacket that was very hard to draw.`,
    fact: 'Sodium combines with chlorine to make ordinary table salt.',
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    family: 'Alkaline earth',
    atomicWeight: '24.305',
    description: `Magnesium is used in fireworks and makes a lot of things explode, so she’s pretty badass. But I feel like once you got to know her, she’d be a really sweet and awesome friend.`,
    fact: 'Magnesium burns with an intense white light and is used in fireworks and flares.',
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    family: 'Metalloid',
    atomicWeight: '28.085',
    description: `Silicon has come into her own as the hot new thing in computers and microchips. Her look is based on a dress from a high-fashion brand—possibly Chanel—that I cannot afford and cannot find on the internet right now, but it kind of looked like computer wires!`,
    fact: 'Silicon is central to computer chips and is the second most abundant element in Earth’s crust.',
  },
  {
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    family: 'Nonmetal',
    atomicWeight: '30.974',
    description: `Phosphorus, mostly known to us in the phosphate group, is pretty maximalist. Traditional and modern Indian fashion has consistently favored maximalism in the form of detailed embroidery, patterned fabrics, and loads of jewelry. I think Phosphorus is most herself in a saree with bold colors and flower patterns, as phosphorus is one of the key ingredients in nature and life!`,
    fact: 'Phosphorus is essential to DNA, cell membranes, and the way living cells store energy.',
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    family: 'Nonmetal',
    atomicWeight: '32.06',
    description: `Sulfur gets way too much hate. She might have an offensive odor in some cases, but in others, she’s essential to your body’s proteins. And in some species, mainly insects, she is used in pheromones to attract mates. So I think Sulfur deserves to be decked out in roses for once!`,
    fact: 'Bright yellow sulfur has been used by people since ancient times.',
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    family: 'Halogen',
    atomicWeight: '35.45',
    description: `If badass was an element, it would be Chlorine. Pools, poison, salt—she’s got it all. I feel I don’t need to explain my choices about her outfit; it’s as extra as she is.`,
    fact: 'Chlorine compounds help disinfect drinking water and swimming pools.',
  },
  {
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    family: 'Noble gas',
    atomicWeight: '39.948',
    description: `Argon’s outfit wasn’t inspired by anything; she kind of just came to me. I think a noble gas wouldn’t be confined to one level of formality or type of clothing. If she wanted to wear a denim top with a silk skirt and scarf, she would. Definitely an unbothered queen.`,
    fact: 'Argon takes its name from a Greek word meaning inactive because it rarely reacts.',
  },
  {
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    family: 'Alkali metal',
    atomicWeight: '39.0983',
    description: `I think I was one of the last generations of kids taught that there was potassium in bananas from Honey, I Shrunk the Kids. So I went for a tropical vibe with Potassium’s fit, with a woven top and a flowy skirt. But I didn’t go bananas with her—she deserves to have a life outside of the fruit!`,
    fact: 'Potassium helps nerves send signals and muscles contract.',
  },
  {
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    family: 'Alkaline earth',
    atomicWeight: '40.078',
    description: `Another childhood chemistry lesson I learned was that calcium was in milk, and that is why milk was good for your bones. So I felt Calcium should be a strong, sturdy gal, which got me thinking about the warriors of ancient Greece and Sparta. Not the most logical train of thought, but check out her cool helmet!`,
    fact: 'Calcium is the most abundant metal in the human body and gives bones their strength.',
  },
  {
    number: 32,
    symbol: 'Ge',
    name: 'Germanium',
    family: 'Metalloid',
    atomicWeight: '72.630',
    description: `Germanium is mostly used in modern technology and is a grayish color, but I did see one photo of light reflecting off some Germanium in brilliant green and pink. Because I was, at the time, obsessed with early 1900s Chinese fashion, I felt that Germanium would look perfect in a look based on vintage cheongsam and qipao. I researched some traditional makeup and added floral patterns because I wanted to add some life to the element’s utility. Just because we study it for fiber optics doesn’t mean we can’t appreciate its beauty.`,
    fact: 'Germanium helped power the first generation of transistors and is still used in fiber optics.',
  },
  {
    number: 33,
    symbol: 'As',
    name: 'Arsenic',
    family: 'Metalloid',
    atomicWeight: '74.9216',
    description: `Clothing dyed with arsenic was very popular in 1800s Europe, and was probably one of the biggest fashion fails ever. While it does give a very beautiful green hue, it’s incredibly toxic and was eventually banned at the end of the century.`,
    fact: 'Arsenic is poisonous, but carefully controlled compounds are valuable in semiconductors.',
  },
  {
    number: 34,
    symbol: 'Se',
    name: 'Selenium',
    family: 'Nonmetal',
    atomicWeight: '78.971',
    description: `Selenium is used in optics technologies, but is also an essential micronutrient for animals, including humans! You can find it most prominently in Brazil nuts, and selenium supports thyroid and overall cell health in humans! So I added a natural element to Selenium’s look with a display of peacock feathers, which were very hard to draw.`,
    fact: 'Selenium is named after Selene, the Greek goddess of the Moon.',
  },
  {
    number: 35,
    symbol: 'Br',
    name: 'Bromine',
    family: 'Halogen',
    atomicWeight: '79.904',
    description: `While Bromine is actually a reddish-brown color in most contexts, I was more inspired by Bromine’s use in pools and industrial water treatment, where it is usually used as a substitute for chlorine. You can also find Bromine in agricultural and other industrial applications.`,
    fact: 'Bromine is the only nonmetal that is liquid at ordinary room temperature.',
  },
  {
    number: 36,
    symbol: 'Kr',
    name: 'Krypton',
    family: 'Noble gas',
    atomicWeight: '83.798',
    description: `Krypton is most famous for its role in the DC Comics universe as Superman’s home planet, as well as in Kryptonite, Superman’s weakness. While Krypton actually glows blue in fluorescent lights, everybody knows this element because of its signature green appearance in comics and movies. It’s incredible how one story can change the whole cultural conception of an element—Krypton is a noble gas, and really isn’t interested in hurting anybody! I still gave Krypton a green look, though, and included Wizard of Oz–esque red heels to represent how fantastical Krypton has become to us.`,
    fact: 'Krypton’s name comes from the Greek word for hidden.',
  },
  {
    number: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    family: 'Alkali metal',
    atomicWeight: '85.4678',
    description: `Even though it is mostly silver or colorless when observed in real life, I saw a photo whose colors reminded me of the fashion of the ancient Inca Empire. The Incas grew from a small group in Peru to control a massive stretch of land along the Pacific coast of South America. Their empire lasted from around the 13th to the 16th century, when Spanish explorers brought both smallpox and political unrest that led to the collapse of the empire. There were many laws in place about the types of clothes one could wear based on one’s social status. Rubidium’s look is inspired by tocapu geometric patterns on dresses and capes that women would often weave themselves for their families or local leaders.`,
    fact: 'Rubidium atoms are used in precise clocks that help keep communications networks in sync.',
  },
  {
    number: 38,
    symbol: 'Sr',
    name: 'Strontium',
    family: 'Alkaline earth',
    atomicWeight: '87.62',
    description: `Strontium’s silvery-white appearance makes for a streetwear-coded look that you could find on a runway or on the streets of Tokyo. Strontium acts very similarly to calcium, and there is ongoing research into its use in supporting bone density for those with osteoporosis and treating bone cancer.`,
    fact: 'Strontium salts create the brilliant crimson color in fireworks.',
  },
  {
    number: 52,
    symbol: 'Te',
    name: 'Tellurium',
    family: 'Metalloid',
    atomicWeight: '127.60',
    description: `Tellurium’s outfit is based on 1990s Chanel and other high-fashion runway looks. This period of fashion included lots of chunky jewelry, fitted vests and skirts, and a lot of tweed. Tellurium definitely took a lot from Naomi Campbell and Claudia Schiffer’s iconic styles from that era.`,
    fact: 'Tellurium is named after tellus, the Latin word for Earth.',
  },
  {
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    family: 'Halogen',
    atomicWeight: '126.90447',
    description: `Iodine is my favorite element, and I felt like I needed to find a look for her based on my own fashion inspirations. One of my favorite movies of all time is Rear Window, directed by Alfred Hitchcock, and Iodine’s outfit is based on just one of the many incredible looks that the female lead, played by Grace Kelly, had to offer. Her costumes were designed by the legendary Edith Head—the inspiration for The Incredibles’ Edna Mode—and they really inspired me to think about the impact clothes can have on a character and the lasting impression they can leave on an era. I also added some purple highlights to Iodine’s outfit to reflect how colorful it can be in its solid form.`,
    fact: 'Iodine forms a striking violet vapor and is essential for healthy thyroid function.',
  },
  {
    number: 54,
    symbol: 'Xe',
    name: 'Xenon',
    family: 'Noble gas',
    atomicWeight: '131.293',
    description: `Xenon, a noble gas, is used in fluorescent lighting and lasers, and can be found in the atmospheres of Jupiter and Saturn. So I thought Xenon’s look should be bedazzled and starry.`,
    fact: 'Xenon can power ion thrusters that gently propel spacecraft over long distances.',
  },
  {
    number: 55,
    symbol: 'Cs',
    name: 'Cesium',
    family: 'Alkali metal',
    atomicWeight: '132.90545',
    description: `The goldish color of cesium metal and the bluish-purple of cesium oxide gave me a color palette for exploring early Islamic fashion. In early Islamic Baghdad, loose tunics and headscarves were popular because they were breathable and protected people from the harsh climate. Clothes were usually made from wool or cotton and had few designs, but those in positions of power imported silk from China to make damask, a richly patterned fabric. Those patterns still influence fashion and home design choices today.`,
    fact: 'The official definition of one second is based on transitions in cesium-133 atoms.',
  },
  {
    number: 56,
    symbol: 'Ba',
    name: 'Barium',
    family: 'Alkaline earth',
    atomicWeight: '137.327',
    description: `Barium is an alkaline earth metal found naturally only in a few minerals on Earth. I thought her look should have a very ethereal quality, as maybe we don’t yet know the full extent of Barium’s uses.`,
    fact: 'Barium sulfate is opaque to X-rays and is used to reveal parts of the digestive system.',
  },
  {
    number: 84,
    symbol: 'Po',
    name: 'Polonium',
    family: 'Post-transition metal',
    atomicWeight: '[209]',
    description: `Named after Marie Curie’s home country of Poland, Polonium is a radioactive element that is extremely poisonous to all life. That’s not her fault, though, so I modeled Polonium after a friend I have who is not radioactive whatsoever.`,
    fact: 'Marie Curie named polonium after her native Poland.',
  },
  {
    number: 85,
    symbol: 'At',
    name: 'Astatine',
    family: 'Halogen',
    atomicWeight: '[210]',
    description: `Astatine has this really pretty—and a bit scary—green color to it that I wanted to incorporate into her look. However, Astatine is one of, if not the, rarest elements on Earth, so I didn’t feel I could make the whole outfit green. Her purse will do just fine.`,
    fact: 'Astatine is so rare that only tiny traces occur naturally in Earth’s crust at any moment.',
  },
  {
    number: 86,
    symbol: 'Rn',
    name: 'Radon',
    family: 'Noble gas',
    atomicWeight: '[222]',
    description: `Radon is a noble gas that is also radioactive. The only logical choice for her outfit was to base it on John Singer Sargent’s 1884 Madame X, a painting of a noblewoman, Virginie Amélie Avegno Gautreau, in a beautiful black dress. In the original painting, one of the dress straps hung off her shoulder, but it was considered so controversial that Sargent had to repaint it to avoid damaging Gautreau’s reputation. Such an interesting story, and the painting itself is absolutely magnificent.`,
    fact: 'Radon is a radioactive noble gas produced naturally as radium decays.',
  },
  {
    number: 87,
    symbol: 'Fr',
    name: 'Francium',
    family: 'Alkali metal',
    atomicWeight: '[223]',
    description: `Francium, like many of the elements with high atomic numbers, is extremely rare. It has this beautiful color, though, that I’m not sure how to describe. It’s like a light rust or an earthy coral. Maybe we should just call that color Francium.`,
    fact: 'Francium is extraordinarily rare and exists naturally only in fleeting traces.',
  },
  {
    number: 88,
    symbol: 'Ra',
    name: 'Radium',
    family: 'Alkaline earth',
    atomicWeight: '[226]',
    description: `I had to do a tribute to Marie Curie in one of these outfits. So why not Radium, the element she discovered and successfully isolated? Curie shared the Nobel Prize in Physics in 1903 and won the Nobel Prize in Chemistry in 1911, coined the term “radioactivity,” and laid the groundwork for early tumor treatments. She is an inspiration to all women, all scientists, and, I think, just everybody.`,
    fact: 'Radium was discovered by Marie and Pierre Curie in 1898.',
  },
];
